"use client"
import './globals.css'
import { ReactNode } from 'react'
import { QueryClient, QueryClientProvider } from 'react-query'

const queryClient = new QueryClient({
  defaultOptions: {
    queries:{
      refetchOnWindowFocus: false
    }
  }}
)


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootProps = {
  children: ReactNode
}

const RootLayout = ({ children }: RootProps) => {
  return (
    <html lang="en" className='h-screen'>
      <body className='flex flex-col bg-gray-900'>
        <QueryClientProvider client={queryClient}>
          {children}
        </QueryClientProvider>
      </body>
    </html>
  )
}

export default RootLayout